-- Multillantas de la Frontera - Supabase Schema

-- 1. Branches Table
CREATE TABLE branches (
  id TEXT PRIMARY KEY, -- e.g., 'matriz', 'poniente', 'sur'
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  manager TEXT NOT NULL,
  phone TEXT NOT NULL,
  schedule TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tires (Inventory Catalog)
CREATE TABLE tires (
  id TEXT PRIMARY KEY,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  width INTEGER NOT NULL,
  profile INTEGER NOT NULL,
  rim INTEGER NOT NULL,
  load_index TEXT NOT NULL,
  speed_rating TEXT NOT NULL,
  type TEXT CHECK (type IN ('AT', 'HT', 'MT')),
  price DECIMAL(10, 2) NOT NULL,
  cost DECIMAL(10, 2) NOT NULL,
  last_movement TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Stock (Junction table for Tires and Branches)
CREATE TABLE stocks (
  tire_id TEXT REFERENCES tires(id) ON DELETE CASCADE,
  branch_id TEXT REFERENCES branches(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (tire_id, branch_id)
);

-- 4. Users Table (Profile data, linked to auth.users if using Auth)
CREATE TABLE user_profiles (
  id UUID PRIMARY KEY, -- Maps to auth.users.id
  name TEXT NOT NULL,
  role TEXT CHECK (role IN ('superadmin', 'gerente', 'contador', 'vendedor')),
  branch_id TEXT REFERENCES branches(id), -- Nullable for superadmins
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Sales
CREATE TABLE sales (
  id TEXT PRIMARY KEY, -- e.g., 'V-2001'
  branch_id TEXT REFERENCES branches(id) NOT NULL,
  seller_id TEXT NOT NULL, -- Name or user_id
  total DECIMAL(10, 2) NOT NULL,
  tax DECIMAL(10, 2) NOT NULL,
  payment_method TEXT CHECK (payment_method IN ('PUE', 'PPD')),
  payment_form TEXT CHECK (payment_form IN ('01', '03', '31', '99')),
  status TEXT CHECK (status IN ('Timbrada', 'Pendiente', 'Cancelada', 'CRP Generado')),
  cfdi_usage TEXT NOT NULL,
  rfc_recuper TEXT NOT NULL,
  date TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Sale Items
CREATE TABLE sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id TEXT REFERENCES sales(id) ON DELETE CASCADE,
  tire_id TEXT REFERENCES tires(id),
  quantity INTEGER NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Transfers
CREATE TABLE transfers (
  id TEXT PRIMARY KEY, -- e.g., 'T-1001'
  origin_branch_id TEXT REFERENCES branches(id),
  destination_branch_id TEXT REFERENCES branches(id),
  tire_id TEXT REFERENCES tires(id),
  quantity INTEGER NOT NULL,
  status TEXT CHECK (status IN ('En tránsito', 'Recibido', 'Cancelado')),
  date TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Warranties
CREATE TABLE warranties (
  id TEXT PRIMARY KEY, -- e.g., 'G-001'
  dot TEXT NOT NULL,
  tire_id TEXT REFERENCES tires(id),
  mileage INTEGER NOT NULL,
  reason TEXT NOT NULL,
  status TEXT CHECK (status IN ('Pendiente', 'Aprobada', 'Rechazada')),
  date TIMESTAMPTZ DEFAULT NOW(),
  photo_url TEXT,
  diagnosis TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE tires ENABLE ROW LEVEL SECURITY;
ALTER TABLE stocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE warranties ENABLE ROW LEVEL SECURITY;

-- Basic Public Read Policies (for demo purposes, restrict later)
CREATE POLICY "Public Read" ON branches FOR SELECT USING (true);
CREATE POLICY "Public Read" ON tires FOR SELECT USING (true);
CREATE POLICY "Public Read" ON stocks FOR SELECT USING (true);
CREATE POLICY "Public Read" ON user_profiles FOR SELECT USING (true);
CREATE POLICY "Public Read" ON sales FOR SELECT USING (true);
CREATE POLICY "Public Read" ON sale_items FOR SELECT USING (true);
CREATE POLICY "Public Read" ON transfers FOR SELECT USING (true);
CREATE POLICY "Public Read" ON warranties FOR SELECT USING (true);
